version: '3.8'

services:
  app:
    build: .
    container_name: patungan_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  worker:
    build: .
    container_name: patungan_worker
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: air -c .air.worker.toml
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: patungan_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=patungan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: patungan_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: patungan_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped

  
  waha:
    image: devlikeapro/waha:latest-2026.1.5
    container_name: patungan_waha
    restart: on-failure
    env_file:
      - .env.waha
    # environment:
    #   - WHATSAPP_DEFAULT_ENGINE=WEBJS
    #   - WAHA_LOG_LEVEL=info
    #   - WAHA_PRINT_QR=True
    ports:
      - "3000:3000"
    volumes:
      - waha_data:/app/sessions

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
  waha_data:
